### ISSUE TITLE
Cannot Launch! Requests to http:// return a 301 redirect to https:// secured Landing Page

### ISSUE THREAD

**Issue by Mbd06b** [ncase/polygons#45]
I've replicated this in Chrome and Firefox, and cannot get past the landing page to reach the actual Playable Post.  

( Landing Page ) https://ncase.me/polygons/ 
( Playable Post ) http://ncase.me/polygons

![image](https://user-images.githubusercontent.com/12649222/200198999-9e0809cf-0bbf-49af-b2a5-a49dd50effbf.png)

(on click of PLAY IT HERE, page simply reloads) 
![image](https://user-images.githubusercontent.com/12649222/200199127-63fd13cd-e77b-425d-92d8-592dc9d19695.png)

**Comment by ncase** [comment]
Aaaaaaaaaaaaaaaaagh

Thank you for sending this issue! Gah, that's embarrassing.

What happened was I accepted a Pull Request for a translation link without testing it locally ( https://github.com/ncase/polygons/commit/816e7dd8485729aaf63dfcf4ba27527ffe388785 ) – the author had accidentally renamed `index.html` to their name, and I failed to notice.  I guess without an `index.html`, GitHub Pages defaults to showing the README.md file.

Anyway, it's been renamed back to `index.html` ( https://github.com/ncase/polygons/commit/3ec3fd74a52ce24f74790a47f117d1a3abefbbb7 ) and so that should have fixed the issue.

Many thanks again, @Mbd06b !
