### ISSUE TITLE
Ideologically forbidden results when set to 100% shapeism

### ISSUE THREAD

**Issue by BrettFederighi** [ncase/polygons#9]
In the "start segregated" bit, you can get to 0% segregation by setting the bias % to 100%.

This is probably an artifact of the fact that the  "% bias" isn't actually a percentage of bias but rather the outcome the shapes are biased against, but if we think too hard about that the whole mathematical parlor trick starts to fall apart.  If it isn't actually some sort of discrimination percentage like the post misleads the reader into believing, then the "small bias" of 30% exhibited by the shapes is really a massive bias against a small set of situations.  Then, the whole "small biases create big outcomes" narrative reduces to "globally-held massive biases create big outcomes" and the whole illusion is broken.

Maybe, in that bit, we should fudge the shapes' movements to make sure the segregation level stays artificially high?  Or maybe just prevent the user from setting bias percent above 50.

**Comment by magicgoose** [comment]
> Maybe, in that bit, we should **fudge the shapes' movements to make sure the segregation level stays artificially high**? Or maybe just prevent the user from setting bias percent above 50.

Wow.
![facepalm](https://cloud.githubusercontent.com/assets/1442206/14484931/e2fc288c-0164-11e6-8b91-a36f2f410c8c.png)

**Comment by foo123** [comment]
This is exactly about ideology isnt it? And a (convenient) interpretation of it. Sorry it's not this way. 

The self-organisation (because that is what it is) of the "polygon socienty" actualy tells nothing about "segregation", "inequality" and all that ("ideologicaly self-serving") jazz. This is an interpretation **on top (and outside) of that** and with no reference tio the base. It is like asking the fish _"how's the water?"_. One can very well feel bad (or good) about fish living in water, but actually says nothing about the fish itself and how much it likes (or dislikes) that and whether it is a good environment to live. Anyway, there is one fact though, that there are (indeed reachable) states where the polygons **are happy** (according to their rules). Whether one would like to call it (or color it if you like) _"segregation"_, _"table"_, _"spaceship"_, _"spaggheti"_, is quite irrelevant as is.

PS. anybody interested in [Flatland](https://en.wikipedia.org/wiki/Flatland) or the ["original" sequel](http://www.amazon.com/Geometry-Relativity-Fourth-Dimension-Mathematics/dp/0486234002)?

And dont forget to wear sunscreen, class of '99 
https://www.youtube.com/watch?v=sTJ7AzBIJoI
